---
.travis.yml:
  forge_password: "W6q1nasHUf2aBI4u6nBrC3LMcrnB8gxf5dBDRqrnC36U1lHH7V8qiaOtDdiUFUSXxVvEB8MuNhwE0F+iCqVnqVc32Jn8k6f0nVFOw6JxeN7T7eXx9TwpomPYIZBwzId4xmD6z/orzAooFozkod7wUjO0mwtvl55VPtBdqz4wnh0="
